### PR TITLE
feat: Allow use on branch without changed js and ts file

### LINKED ISSUE #34: diff runner breaks if there is no file to be mutated
When running stryker-diff-runner, and the current branch has no changed .js file, stryker-diff-runner breaks the execution instead of sending an empty list of files, leaving the stryker to decide what to do.

## To simulate:
1. Clone the '_mutation-diff_' branch of my ServeRest repository: https://github.com/PauloGoncalvesBH/ServeRest/tree/mutation-diff
2. Run 'npm install' and 'npm run test: mutation: diff'
3. At this point, the execution of stryker-diff-runner will break, as this branch has only 1 commit above the trunk branch, and no changes to the .js file.

## Evidences:

[From line 83 of the pipeline execution result](https://github.com/PauloGoncalvesBH/ServeRest/runs/1450200137?check_suite_focus=true#step:5:83)

image

### PR DESCRIPTION
**Pull request by PauloGoncalvesBH**
If there is no altered file, stryker-diff-runner will be aborted and will not result in a break, allowing use in the pipeline.

image

It will also validate if the branch passed in the '--branch' argument exists, otherwise the execution will be aborted in error.

image

closes #34

### CODE REVIEW

**Comment by PauloGoncalvesBH** [comment]
@tverhoken I tried and failed to implement unit tests. I must try again in a few days (my time is well spent).

**Comment by tverhoken** [comment]
Alright, I wait for tests update before going further with the review 😉

**Comment by PauloGoncalvesBH** [comment]
@tverhoken, I implemented the missing unit tests and corrected the current ones that started to break with my implementation.
I didn't understand why the code coverage says that lines 24 and 25 are not covered when there are tests that pass through them. Even when running the test locally displays the error message on line 25.

image

**Comment by PauloGoncalvesBH** [comment]
@tverhoken I saw that you are not '_watching_' this repository, so I believe it is difficult to see these updates.

**Comment by PauloGoncalvesBH** [comment]
@tverhoken, I implemented the missing unit tests and corrected the current ones that started to break with my implementation.
**Is ready for your review** 🥳

**Review by tverhoken — APPROVED** [review]
Nice job 😃

**Pull request merged**
